export interface SearchPage {
  href: string;
  labelEs: string;
  labelEn: string;
  categoryEs: string;
  categoryEn: string;
  keywordsEs: string[];
  keywordsEn: string[];
  descriptionEs: string;
  descriptionEn: string;
}

export const SEARCH_INDEX: SearchPage[] = [
  // ── Main pages ──
  {
    href: "/",
    labelEs: "Inicio", labelEn: "Home",
    categoryEs: "Navegación", categoryEn: "Navigation",
    keywordsEs: ["inicio", "home", "medellin", "medellín", "ciudad", "destino", "turismo", "viaje", "hospitalidad", "colombia", "principal", "bienvenida"],
    keywordsEn: ["home", "start", "medellin", "city", "destination", "tourism", "travel", "hospitality", "colombia", "welcome"],
    descriptionEs: "Página principal de Allura Healthcare en Medellín, Colombia.",
    descriptionEn: "Allura Healthcare home page in Medellín, Colombia.",
  },
  {
    href: "/como-funciona",
    labelEs: "Cómo funciona", labelEn: "How it works",
    categoryEs: "Navegación", categoryEn: "Navigation",
    keywordsEs: ["como funciona", "proceso", "pasos", "viaje medico", "turismo medico", "coordinacion", "reserva", "planificacion", "experiencia"],
    keywordsEn: ["how it works", "process", "steps", "medical journey", "medical tourism", "coordination", "booking", "planning", "experience"],
    descriptionEs: "Conoce el proceso paso a paso para tu viaje médico con Allura.",
    descriptionEn: "Learn the step-by-step process for your medical journey with Allura.",
  },
  {
    href: "/nosotros",
    labelEs: "Sobre nosotros", labelEn: "About us",
    categoryEs: "Navegación", categoryEn: "Navigation",
    keywordsEs: ["nosotros", "sobre allura", "filosofia", "filosofía", "valores", "mision", "misión", "vision", "visión", "historia", "quienes somos", "identidad", "proposito", "propósito", "equipo directivo"],
    keywordsEn: ["about", "about allura", "philosophy", "values", "mission", "vision", "history", "who we are", "identity", "purpose", "leadership"],
    descriptionEs: "Conoce la filosofía, misión, visión e historia detrás de Allura Healthcare.",
    descriptionEn: "Discover the philosophy, mission, vision, and history behind Allura Healthcare.",
  },
  {
    href: "/equipo",
    labelEs: "Nuestro equipo", labelEn: "Our team",
    categoryEs: "Navegación", categoryEn: "Navigation",
    keywordsEs: ["equipo", "doctores", "medicos", "especialistas", "cirujanos", "odontologos", "profesionales", "staff", "facultad"],
    keywordsEn: ["team", "doctors", "physicians", "specialists", "surgeons", "dentists", "professionals", "staff", "faculty"],
    descriptionEs: "Conoce a nuestros médicos y especialistas certificados.",
    descriptionEn: "Meet our certified doctors and specialists.",
  },
  {
    href: "/contacto",
    labelEs: "Contáctanos", labelEn: "Contact us",
    categoryEs: "Navegación", categoryEn: "Navigation",
    keywordsEs: ["contacto", "contactar", "consulta", "cita", "reserva", "whatsapp", "email", "telefono", "teléfono", "mensaje", "agendar"],
    keywordsEn: ["contact", "consultation", "appointment", "booking", "whatsapp", "email", "phone", "message", "schedule"],
    descriptionEs: "Agenda tu consulta o escríbenos para más información.",
    descriptionEn: "Schedule your consultation or write to us for more information.",
  },
  {
    href: "/blog",
    labelEs: "Blog", labelEn: "Blog",
    categoryEs: "Navegación", categoryEn: "Navigation",
    keywordsEs: ["blog", "articulos", "artículos", "noticias", "consejos", "salud", "bienestar", "lectura"],
    keywordsEn: ["blog", "articles", "news", "tips", "health", "wellness", "reading"],
    descriptionEs: "Artículos sobre salud, bienestar y turismo médico.",
    descriptionEn: "Articles on health, wellness, and medical tourism.",
  },

  // ── Service hubs ──
  {
    href: "/servicios",
    labelEs: "Servicios", labelEn: "Services",
    categoryEs: "Servicios", categoryEn: "Services",
    keywordsEs: ["servicios", "tratamientos", "procedimientos", "catalogo", "catálogo", "especialidades"],
    keywordsEn: ["services", "treatments", "procedures", "catalogue", "specialties"],
    descriptionEs: "Todos los servicios médicos y estéticos de Allura.",
    descriptionEn: "All medical and aesthetic services at Allura.",
  },
  {
    href: "/servicios/full-mouth-reconstruction",
    labelEs: "Full Mouth Reconstruction", labelEn: "Full Mouth Reconstruction",
    categoryEs: "Servicios", categoryEn: "Services",
    keywordsEs: ["reconstruccion", "reconstrucción", "boca completa", "rehabilitacion bucal", "rehabilitación bucal", "implantes", "protesis", "prótesis", "dental completo"],
    keywordsEn: ["reconstruction", "full mouth", "oral rehabilitation", "implants", "prosthetics", "complete dental"],
    descriptionEs: "Reconstrucción completa de la boca con implantes y prótesis.",
    descriptionEn: "Complete mouth reconstruction with implants and prosthetics.",
  },
  {
    href: "/servicios/smile-makeover",
    labelEs: "Smile Makeover", labelEn: "Smile Makeover",
    categoryEs: "Servicios", categoryEn: "Services",
    keywordsEs: ["diseño de sonrisa", "sonrisa perfecta", "estetica dental", "estética dental", "carillas", "coronas", "blanqueamiento", "smile makeover"],
    keywordsEn: ["smile design", "perfect smile", "dental aesthetics", "veneers", "crowns", "whitening", "smile makeover"],
    descriptionEs: "Transforma tu sonrisa con nuestros tratamientos estéticos dentales.",
    descriptionEn: "Transform your smile with our dental aesthetic treatments.",
  },
  {
    href: "/servicios/aligners",
    labelEs: "Alineadores (Aligners)", labelEn: "Aligners",
    categoryEs: "Servicios", categoryEn: "Services",
    keywordsEs: ["alineadores", "ortodoncia invisible", "invisalign", "dientes torcidos", "correccion dental", "corrección dental", "brackets invisibles"],
    keywordsEn: ["aligners", "invisible orthodontics", "invisalign", "crooked teeth", "dental correction", "clear braces"],
    descriptionEs: "Alineadores transparentes e Invisalign para una sonrisa perfecta.",
    descriptionEn: "Clear aligners and Invisalign for a perfect smile.",
  },
  {
    href: "/servicios/facial-harmony",
    labelEs: "Facial Harmony", labelEn: "Facial Harmony",
    categoryEs: "Servicios", categoryEn: "Services",
    keywordsEs: ["armonia facial", "armonización facial", "armonizacion facial", "botox", "estetica facial", "estética facial", "cirugia estetica", "cirugía estética", "rellenos", "rejuvenecimiento"],
    keywordsEn: ["facial harmony", "facial aesthetics", "botox", "facial surgery", "fillers", "rejuvenation", "facelift"],
    descriptionEs: "Procedimientos de armonización y estética facial.",
    descriptionEn: "Facial harmonization and aesthetic procedures.",
  },

  // ── Full Mouth Reconstruction ──
  {
    href: "/servicios/full-mouth-reconstruction/implantes-unitarios",
    labelEs: "Implantes Unitarios", labelEn: "Single Implants",
    categoryEs: "Full Mouth Reconstruction", categoryEn: "Full Mouth Reconstruction",
    keywordsEs: ["implante unitario", "diente perdido", "implante dental", "oseointegración", "corona sobre implante"],
    keywordsEn: ["single implant", "missing tooth", "dental implant", "osseointegration", "implant crown"],
    descriptionEs: "Reemplazo de un diente perdido con implante dental unitario.",
    descriptionEn: "Replacement of a single missing tooth with a dental implant.",
  },
  {
    href: "/servicios/full-mouth-reconstruction/implantes-all-on-x",
    labelEs: "Implantes All-on-X", labelEn: "All-on-X Implants",
    categoryEs: "Full Mouth Reconstruction", categoryEn: "Full Mouth Reconstruction",
    keywordsEs: ["all on 4", "all on 6", "all on x", "arco completo", "dentadura fija", "protesis total", "prótesis total"],
    keywordsEn: ["all on 4", "all on 6", "all on x", "full arch", "fixed denture", "total prosthetics"],
    descriptionEs: "Arco dental completo fijo sobre 4 o 6 implantes.",
    descriptionEn: "Full fixed dental arch on 4 or 6 implants.",
  },
  {
    href: "/servicios/full-mouth-reconstruction/rehabilitacion-oral-completa",
    labelEs: "Rehabilitación Oral Completa", labelEn: "Full Oral Rehabilitation",
    categoryEs: "Full Mouth Reconstruction", categoryEn: "Full Mouth Reconstruction",
    keywordsEs: ["rehabilitacion oral", "rehabilitación oral", "boca completa", "tratamiento integral", "reconstruccion total", "reconstrucción total"],
    keywordsEn: ["oral rehabilitation", "full mouth", "comprehensive treatment", "total reconstruction"],
    descriptionEs: "Tratamiento integral para la rehabilitación completa de la boca.",
    descriptionEn: "Comprehensive treatment for complete oral rehabilitation.",
  },
  {
    href: "/servicios/full-mouth-reconstruction/protesis-fijas",
    labelEs: "Prótesis Fijas", labelEn: "Fixed Prosthetics",
    categoryEs: "Full Mouth Reconstruction", categoryEn: "Full Mouth Reconstruction",
    keywordsEs: ["protesis fija", "prótesis fija", "corona fija", "puente dental", "dentadura fija"],
    keywordsEn: ["fixed prosthetics", "fixed crown", "dental bridge", "fixed denture"],
    descriptionEs: "Prótesis dentales fijas de alta calidad.",
    descriptionEn: "High-quality fixed dental prosthetics.",
  },
  {
    href: "/servicios/full-mouth-reconstruction/reemplazo-restauraciones",
    labelEs: "Reemplazo de Restauraciones", labelEn: "Restoration Replacement",
    categoryEs: "Full Mouth Reconstruction", categoryEn: "Full Mouth Reconstruction",
    keywordsEs: ["reemplazo restauraciones", "cambio coronas", "reparacion dental", "reparación dental", "amalgama", "resina"],
    keywordsEn: ["restoration replacement", "crown replacement", "dental repair", "amalgam", "resin"],
    descriptionEs: "Reemplazo y mejora de restauraciones dentales existentes.",
    descriptionEn: "Replacement and improvement of existing dental restorations.",
  },
  {
    href: "/servicios/full-mouth-reconstruction/planificacion-digital-3d",
    labelEs: "Planificación Digital 3D", labelEn: "3D Digital Planning",
    categoryEs: "Full Mouth Reconstruction", categoryEn: "Full Mouth Reconstruction",
    keywordsEs: ["planificacion 3d", "planificación 3d", "diagnostico digital", "diagnóstico digital", "simulacion", "simulación", "tecnologia dental", "tecnología dental"],
    keywordsEn: ["3d planning", "digital diagnosis", "simulation", "dental technology"],
    descriptionEs: "Diagnóstico y planificación de tratamientos con tecnología 3D.",
    descriptionEn: "Diagnosis and treatment planning with 3D technology.",
  },

  // ── Smile Makeover ──
  {
    href: "/servicios/smile-makeover/carillas-porcelana",
    labelEs: "Carillas de Porcelana", labelEn: "Porcelain Veneers",
    categoryEs: "Smile Makeover", categoryEn: "Smile Makeover",
    keywordsEs: ["carillas", "porcelana", "laminados", "facetas", "dientes blancos", "estetica dental", "estética dental"],
    keywordsEn: ["veneers", "porcelain", "laminates", "facets", "white teeth", "dental aesthetics"],
    descriptionEs: "Carillas de porcelana para un aspecto natural y brillante.",
    descriptionEn: "Porcelain veneers for a natural, bright appearance.",
  },
  {
    href: "/servicios/smile-makeover/diseno-digital-sonrisa",
    labelEs: "Diseño Digital de Sonrisa", labelEn: "Digital Smile Design",
    categoryEs: "Smile Makeover", categoryEn: "Smile Makeover",
    keywordsEs: ["diseño de sonrisa", "dsd", "simulacion sonrisa", "simulación sonrisa", "smile design", "planificacion estetica", "planificación estética"],
    keywordsEn: ["smile design", "dsd", "smile simulation", "aesthetic planning"],
    descriptionEs: "Planificación digital personalizada para tu nueva sonrisa.",
    descriptionEn: "Personalized digital planning for your new smile.",
  },
  {
    href: "/servicios/smile-makeover/coronas-porcelana",
    labelEs: "Coronas de Porcelana", labelEn: "Porcelain Crowns",
    categoryEs: "Smile Makeover", categoryEn: "Smile Makeover",
    keywordsEs: ["coronas", "porcelana", "funda dental", "restauracion estetica", "restauración estética", "diente roto"],
    keywordsEn: ["crowns", "porcelain", "dental cap", "aesthetic restoration", "broken tooth"],
    descriptionEs: "Coronas de porcelana estéticas y duraderas.",
    descriptionEn: "Aesthetic and durable porcelain crowns.",
  },
  {
    href: "/servicios/smile-makeover/restauraciones-esteticas",
    labelEs: "Restauraciones Estéticas", labelEn: "Aesthetic Restorations",
    categoryEs: "Smile Makeover", categoryEn: "Smile Makeover",
    keywordsEs: ["restauracion", "restauración", "relleno dental", "composite", "resina", "caries", "empaste estetico", "empaste estético"],
    keywordsEn: ["restoration", "dental filling", "composite", "resin", "cavity", "aesthetic filling"],
    descriptionEs: "Restauraciones dentales con materiales estéticos de última generación.",
    descriptionEn: "Dental restorations with state-of-the-art aesthetic materials.",
  },
  {
    href: "/servicios/smile-makeover/blanqueamiento-dental",
    labelEs: "Blanqueamiento Dental", labelEn: "Teeth Whitening",
    categoryEs: "Smile Makeover", categoryEn: "Smile Makeover",
    keywordsEs: ["blanqueamiento", "dientes blancos", "aclaramiento dental", "whitening", "manchas dentales"],
    keywordsEn: ["whitening", "white teeth", "teeth bleaching", "dental stains"],
    descriptionEs: "Blanqueamiento dental profesional para una sonrisa radiante.",
    descriptionEn: "Professional teeth whitening for a radiant smile.",
  },

  // ── Aligners ──
  {
    href: "/servicios/aligners/invisalign",
    labelEs: "Invisalign", labelEn: "Invisalign",
    categoryEs: "Alineadores", categoryEn: "Aligners",
    keywordsEs: ["invisalign", "alineadores invisibles", "ortodoncia invisible", "dientes alineados"],
    keywordsEn: ["invisalign", "invisible aligners", "invisible orthodontics", "straight teeth"],
    descriptionEs: "Ortodoncia invisible con la marca Invisalign.",
    descriptionEn: "Invisible orthodontics with the Invisalign brand.",
  },
  {
    href: "/servicios/aligners/alineadores-transparentes",
    labelEs: "Alineadores Transparentes", labelEn: "Clear Aligners",
    categoryEs: "Alineadores", categoryEn: "Aligners",
    keywordsEs: ["alineadores transparentes", "ortodoncia sin brackets", "placas removibles", "ferula ortodoncia", "férula ortodoncia"],
    keywordsEn: ["clear aligners", "bracketless orthodontics", "removable plates", "orthodontic retainer"],
    descriptionEs: "Alineadores transparentes removibles para corregir tu mordida.",
    descriptionEn: "Removable clear aligners to correct your bite.",
  },
  {
    href: "/servicios/aligners/escaneo-digital-3d",
    labelEs: "Escaneo Digital 3D", labelEn: "3D Digital Scan",
    categoryEs: "Alineadores", categoryEn: "Aligners",
    keywordsEs: ["escaneo 3d", "scanner dental", "impresion digital", "impresión digital", "modelo digital", "itero"],
    keywordsEn: ["3d scan", "dental scanner", "digital impression", "digital model", "itero"],
    descriptionEs: "Escaneo dental 3D de precisión sin moldes tradicionales.",
    descriptionEn: "Precision 3D dental scanning without traditional molds.",
  },
  {
    href: "/servicios/aligners/planificacion-personalizada",
    labelEs: "Planificación Personalizada", labelEn: "Personalized Planning",
    categoryEs: "Alineadores", categoryEn: "Aligners",
    keywordsEs: ["planificacion personalizada", "planificación personalizada", "plan de tratamiento", "diseño de movimiento", "simulacion dental", "simulación dental"],
    keywordsEn: ["personalized planning", "treatment plan", "movement design", "dental simulation"],
    descriptionEs: "Plan de tratamiento personalizado para tu caso específico.",
    descriptionEn: "Personalized treatment plan for your specific case.",
  },
  {
    href: "/servicios/aligners/seguimiento-remoto",
    labelEs: "Seguimiento Remoto", labelEn: "Remote Follow-up",
    categoryEs: "Alineadores", categoryEn: "Aligners",
    keywordsEs: ["seguimiento remoto", "control online", "teleconsulta", "citas virtuales", "monitoreo", "app dental"],
    keywordsEn: ["remote follow-up", "online control", "teleconsultation", "virtual appointments", "monitoring", "dental app"],
    descriptionEs: "Seguimiento de tu tratamiento a distancia con nuestra app.",
    descriptionEn: "Track your treatment remotely with our app.",
  },

  // ── Facial Harmony ──
  {
    href: "/servicios/facial-harmony/evaluacion-facial",
    labelEs: "Evaluación Facial", labelEn: "Facial Evaluation",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["evaluacion facial", "evaluación facial", "diagnostico facial", "diagnóstico facial", "analisis facial", "análisis facial", "consulta estetica", "consulta estética"],
    keywordsEn: ["facial evaluation", "facial diagnosis", "facial analysis", "aesthetic consultation"],
    descriptionEs: "Evaluación integral de tu rostro para diseñar el plan de armonización.",
    descriptionEn: "Comprehensive facial evaluation to design your harmonization plan.",
  },
  {
    href: "/servicios/facial-harmony/toxina-botulinica",
    labelEs: "Toxina Botulínica", labelEn: "Botulinum Toxin",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["botox", "toxina botulinica", "toxina botulínica", "arrugas", "expresion", "expresión", "rejuvenecimiento facial", "neuromodulador"],
    keywordsEn: ["botox", "botulinum toxin", "wrinkles", "expression", "facial rejuvenation", "neuromodulator"],
    descriptionEs: "Aplicación de toxina botulínica para suavizar arrugas de expresión.",
    descriptionEn: "Botulinum toxin application to smooth expression wrinkles.",
  },
  {
    href: "/servicios/facial-harmony/bioestimuladores",
    labelEs: "Bioestimuladores", labelEn: "Biostimulators",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["bioestimuladores", "colageno", "colágeno", "sculptra", "radiesse", "elastina", "regeneracion", "regeneración", "piel firme"],
    keywordsEn: ["biostimulators", "collagen", "sculptra", "radiesse", "elastin", "regeneration", "firm skin"],
    descriptionEs: "Bioestimuladores para mejorar la calidad y firmeza de la piel.",
    descriptionEn: "Biostimulators to improve skin quality and firmness.",
  },
  {
    href: "/servicios/facial-harmony/blefaroplastia",
    labelEs: "Blefaroplastia", labelEn: "Blepharoplasty",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["blefaroplastia", "parpados", "párpados", "cirugia parpados", "cirugía párpados", "parpados caidos", "párpados caídos", "ojos cansados"],
    keywordsEn: ["blepharoplasty", "eyelids", "eyelid surgery", "droopy eyelids", "tired eyes"],
    descriptionEs: "Corrección quirúrgica de párpados caídos para una mirada rejuvenecida.",
    descriptionEn: "Surgical correction of droopy eyelids for a rejuvenated look.",
  },
  {
    href: "/servicios/facial-harmony/rinoplastia",
    labelEs: "Rinoplastia", labelEn: "Rhinoplasty",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["rinoplastia", "cirugia nariz", "cirugía nariz", "nariz", "rinomodelacion", "rinomodelación", "septoplastia"],
    keywordsEn: ["rhinoplasty", "nose surgery", "nose job", "nose reshaping", "septoplasty"],
    descriptionEs: "Rinoplastia estética y funcional para modelar tu nariz.",
    descriptionEn: "Aesthetic and functional rhinoplasty to reshape your nose.",
  },
  {
    href: "/servicios/facial-harmony/lifting-facial",
    labelEs: "Lifting Facial", labelEn: "Facelift",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["lifting facial", "facelift", "estiramiento facial", "rejuvenecimiento facial", "flacidez", "ptosis facial"],
    keywordsEn: ["facelift", "facial lifting", "facial rejuvenation", "skin laxity", "facial ptosis"],
    descriptionEs: "Lifting facial quirúrgico para un aspecto más joven y natural.",
    descriptionEn: "Surgical facelift for a younger and natural appearance.",
  },
  {
    href: "/servicios/facial-harmony/mentoplastia",
    labelEs: "Mentoplastia", labelEn: "Mentoplasty",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["mentoplastia", "menton", "mentón", "barbilla", "implante menton", "implante mentón", "aumento menton", "aumento mentón"],
    keywordsEn: ["mentoplasty", "chin", "chin implant", "chin augmentation", "chin surgery"],
    descriptionEs: "Cirugía de mentón para mejorar el perfil y la armonía facial.",
    descriptionEn: "Chin surgery to improve the profile and facial harmony.",
  },
  {
    href: "/servicios/facial-harmony/cirugia-maxilofacial",
    labelEs: "Cirugía Maxilofacial", labelEn: "Maxillofacial Surgery",
    categoryEs: "Facial Harmony", categoryEn: "Facial Harmony",
    keywordsEs: ["cirugia maxilofacial", "cirugía maxilofacial", "mandibula", "mandíbula", "maxilar", "ortognatica", "ortognática", "mordida", "correccion osea", "corrección ósea"],
    keywordsEn: ["maxillofacial surgery", "jaw", "maxillary", "orthognathic", "bite correction", "bone correction"],
    descriptionEs: "Cirugía maxilofacial para corregir estructuras óseas del rostro.",
    descriptionEn: "Maxillofacial surgery to correct facial bone structures.",
  },
];
